//AutoGenerated Begin
//DO NOT EDIT!
package simx.components.editor.gui

import scala.swing._
import simx.core.entity.description.SValSet

class SValSetSVarViewGenerator59c2a78e77fe48bb90de6b71dfaf0d94 extends SVarViewGenerator[SValSet] {

  def generate: SVarView[SValSet] = new SVarView[SValSet] {

//AutoGenerated END
//Put your code below

    /**
     *  The scala.swing.Component that visualizes the value.
     */
    val textArea = new TextArea()
    val component = new ScrollPane(textArea)

    /**
      *  This function is called whenever the visualized value changes.
      *  It should update component accordingly.
      */
    def update(sVarValue: SValSet) {
      textArea.text = ""
      sVarValue.keySet.foreach(Symbol => textArea.text += Symbol.name + " => " + sVarValue.get(Symbol).get.toString() + "\r\n")
    }
  }

  /**
   *  The name of this visualizer.
   *  This must not be unique.
   */
  val name: String = "Register View"

}